<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EcuNexo.Platform.Core\EcuNexo.Platform.Core.csproj" />
    <ProjectReference Include="..\EcuNexo.Platform.Business\EcuNexo.Platform.Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>EcuNexo.Platform.Data</RootNamespace>
    <NoWarn>$(NoWarn);IDE0161;CA1861;IDE0005</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Licensing\Migrations\**\*.cs">
      <NoWarn>$(NoWarn);IDE0161;CA1861;IDE0005</NoWarn>
    </Compile>
  </ItemGroup>

</Project>
